# Generated by Django 4.1.3 on 2022-11-10 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=None, null=True, related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
